### ISSUE TITLE
CNAME is broken

### ISSUE THREAD

**Issue by neilparikh** [Code52/code52.github.com#8]
When I go to code52.github.com, I get the error "Firefox can't find the server at code52.orgwww.code52.org." That's probably because you have both code52.org and www.code52.org in your CNAME file.

**Comment by neilparikh** [comment]
Also www.code52.org comes up with a github pages error "Page not found".

**Comment by andrewtobin** [comment]
Thanks Neil, we're seriously trying to figure out what the heck is going on, I might have to ping someone at github... fixed the CNAME but still no joy as yet (I'm on a corporate cached server, so ... might not see for a while)

**Comment by neilparikh** [comment]
Does having 2 urls in your CNAME file work?

**Comment by neilparikh** [comment]
Oh and www.code52.org seems to work now.

**Comment by neilparikh** [comment]
But not code52.github.com.

**Comment by andrewtobin** [comment]
Apparently not!

code52.org working here, www.code52.org sometimes working - seemingly depending on browser can auto-redirect... code52.github.com working fine here.

**Comment by neilparikh** [comment]
Okay, I tried it in Chrome and Safari, and it works fine in both. It just doesn't work in Firefox for some reason. I'll try installing a completely fresh version of Firefox to see if its because my configuration.

**Comment by neilparikh** [comment]
Okay, it started working now Firefox too. I tried all three to make sure and they all seem to be working. It might have been a temporary issue.
